### ISSUE TITLE
www.robbinfan.com 并没有正常打开

### ISSUE THREAD

**Issue by msl12** [robbin/robbin_site#11]
http://robbinfan.com/ 这个网址是您的博客网址，当然可以正常开启。

但是，http://www.robbinfan.com/ 这个网址呢，打开后显示 **Welcome to nginx!**

我看了下您的 _nginx.conf_ 文件里的内容，这两个网址都是您的域名。

**Comment by robbin** [comment]
域名备案太严格，关站了。
