### ISSUE TITLE
网络io开销

### ISSUE THREAD

**Issue by huangxingle2009** [robbin/robbin_site#13]
我是做phper， 本来很多是联表查询的，现在改成单表查询后，在遍历查询其他表信息。 一个列表页面，需要执行的sql 要达到 800多条，时间要2秒钟左右。 后来查询原因 是网络io 开销太大了， 800条来来回回，所有碰到这个问题。 我的qq：3314308761

**Comment by robbin** [comment]
800多条？要么你的需求有问题，要么你的程序有问题。除非了OLAP，否则不可能需要800条这么多数据量一次性提取出来
