### ISSUE TITLE
无法捕获ActiveRecord::RecordNotFound错误

### ISSUE THREAD

**Issue by CicholGricenchos** [robbin/robbin_site#7]
robbin你好，我在写自己博客的时候参照了你的一个写法

``` ruby
error ActiveRecord::RecordNotFound do
  halt 404
end
```

然而这个写法实际上无法捕获错误，我在你线上的博客上测试了一下，输入了一个不存在的文章id

http://robbinfan.com/blog/100

并没有返回友好错误提示，翻了很久padrino的文档也没找到关于RecordNotFound的处理，想请教一下这个问题应该如何解决呢？

**Comment by robbin** [comment]
框架的问题，等待Padrino自己修复。
